### ISSUE TITLE
Add ability to check combobox store contents

### ISSUE THREAD

**Issue by tjpalmer85** [westy/pyseext#8]
In store_helper.py there is a "placeholder" for a method that checks the contents of a store. It would be great if this was developed so it could be used in scenarios where we want to check a combox only contains certain elements.

If it was to do what the idea said "Method that checks that the store contains the specified data, and optionally only the specified data." that would be ideal and would mean we could move away from having to use applitools for this scenario.

**Comment by westy** [comment]
Well, that was a little harder than I was expecting, but think it's there now.
I'll tag another release so you can update your requirements.txt and give it a go.
