### ISSUE TITLE
Add ability to check menu items visible without clicking them

### ISSUE THREAD

**Issue by psuryateja123** [westy/pyseext#9]
Need to have an ability to check the menu items that are visible after right clicking on an item in tree panel. So something by passing the expected menu items to be enable could return true and unexpected to be returned false

**Comment by westy** [comment]
Added a method to TreeHelper class.
Details here: https://westy.github.io/pyseext/tree_helper.html#pyseext.tree_helper.TreeHelper.check_node_context_menu_contains_items

**Comment by westy** [comment]
In release 1.0.4
